### ISSUE TITLE
SLIPPacketSerial send() gives me two 0xc0 as the end of packet

### ISSUE THREAD

**Issue by latonita** [bakercp/PacketSerial#11]
I simply do slip.send(buff*,size) and it gives me nice slip packet, but with two 0xc0 in the end instead of one. this makes stream desynchronized and i loose packets on receiving side

I suppose it shall be only one 0xc0 in the end.

what i get:
[0xc0,data,0xc0,0xc0][0xc0,data,0xc0,0xc0]...

what i expect:
[0xc0,data,0xc0][0xc0,data,0xc0]...

thanks

**Comment by bakercp** [comment]
Hey there, thanks for the report -- can you test this pull request to see if it fixes the issue?  I haven't had a chance to test it.  If it works, we should just merge it!

https://github.com/bakercp/PacketSerial/pull/7

**Comment by latonita** [comment]
@bakercp please review and merge my fix #12

**Comment by bakercp** [comment]
I'm checking it out now.  Thanks!

**Comment by bakercp** [comment]
I believe everything should be in order now.  Please check out the latest release.

Thanks for your contribution.
