### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by silardg** [bakercp/PacketSerial#15]
I would like to connect my arduino and raspberry pi together using this protocol.

Has anyone managed to create the code for the raspberry pi (with pyserial or wiringPi)

Thanks!

**Comment by bakercp** [comment]
Hey there, yes, people have used this library on the Raspberry Pi using both openFrameworks and also python.  See the [compatible libraries section](https://github.com/bakercp/PacketSerial/blob/master/README.md#tested-compatible-libraries) of the README.

Any library that implements the COBS or SLIP framing protocols should work.
