### ISSUE TITLE
Serial is not sending data

### ISSUE THREAD

**Issue by gadLinux** [bakercp/PacketSerial#16]
Hi, 
I'm using this great library to make USB-Serial binary protocol. I found that .flush() is not working properly and there's no way to flush data to the link. 

The only thing I found it working is adding a Serial.println(); after each PacketSerial.send(). Something that adds \r\n of course but at least I can see the data on the other side of the serial link. 
Do you think is something wrong with latest versions of arduino lib? 1.8.X

**Comment by bakercp** [comment]
Hm ... I'm not sure without seeing the code, hardware setup etc.

**Comment by bakercp** [comment]
Closing this issue for now due to no new information. Please reopen if it's still an issue.
