### ISSUE TITLE
Sending over serial stops

### ISSUE THREAD

**Issue by kyoreth** [bakercp/PacketSerial#18]
Hey! I'm using this library to send 44 bytes as a packet over serial. Smaller size packets work fine, however the full data of 44 bytes causes the arduino to stop sending packets beyond a few. For example, on the pc end i use a python script to read 45 bytes, output to screen, then read 45 more. This works the first 24 or 25 times, then stops. I've tried inserting Serial.flush(), and a 1000ms delay, however it is still no go. 
[imu_logger_mk2.zip](https://github.com/bakercp/PacketSerial/files/2530247/imu_logger_mk2.zip)

**Comment by kyoreth** [comment]
I should mention its running off of a arduino uno

**Comment by kyoreth** [comment]
Durr, pointer error. Sorry for the post!

**Comment by bakercp** [comment]
Aha, glad you got it figured out :)
