### ISSUE TITLE
Seeing strange behavior ... looking for thoughts ...

### ISSUE THREAD

**Issue by Humancell** [bakercp/PacketSerial#20]
Hello,

I've been using PacketSerial with great results, and have now ran into a problem that I'm trying to debug.

I'm connecting a Moteino with a ESP8266 ESP-12F.  Both are using SoftwareSerial.  I'm receiving packets from a radio, and putting it into a structure where I add a CRC32.  The "packets" end up being 109 bytes.  I've created a simple ACK/NAK protocol with 3 retries.

When sending through PacketSerial there are two issues that I am seeing in this particular project that are blowing my mind.  Almost ALL packets are going through just fine.  Sometimes - randomly - a packet does NOT go through and there are two different symptoms:

1. Sometimes I get nothing at all on the receiving side.  Even across the 3 retries.

2. Sometimes I get a 0 byte length packet, followed by 172 byte packet.  Should I really see a 0 byte length packet?

I've now added a 2 second "heartbeat" packet that is 5 bytes long.  These seem to work every single time ... no problems.  So I see 5 byte packets every two seconds, then I'll get a 109 byte packet, and then back to the 5 byte packets.  And this goes on for minutes and then I'll get one of the two cases above.

I've flooded my code with debug output and just can't see where this could be failing.  I can't think of how - when I see 3 retries of 109 byte packets - the receiving event handler would not fire.  Nor can I understand where/how I would ever see 0 byte packets?

I'm not saying it's in the library, but looking for any thoughts or ideas of where I ought to be looking.  I appreciate any input.

**Comment by Humancell** [comment]
I'm going to close this out ... as I have figured out one of the issues ... I still do not understand the other.

1. It turns out that the WiFi operations on the ESP8266 were taking too long for the flow of packets.  As they took control for 7-8 seconds, the packets being received were being overwritten or lost.

2. I still can not quite understand why I sometimes get packets of 0 length.  It seems this would normally be some sort of error condition.  I'm not able to determine what is causing this.

I'm making progress, but now have two other issues that I've come across ...  :-)

**Comment by bakercp** [comment]
Checking out the other issues.  Sorry for the delay.
