### ISSUE TITLE
Add CRC checksum

### ISSUE THREAD

**Issue by wizard97** [bakercp/PacketSerial#6]
The SLIP and COBS encoding is great for aligning with streams, but it doesn't guarantee there are not any errors. It would be great if this library could automatically calculate and append a CRC, so the receiver can automatically throw away messages with errors.

**Comment by bakercp** [comment]
Currently I am not automatically adding checksums for performance reasons, but it is easy enough to do manually with a library like https://github.com/bakercp/crc32.  (That's how I'm doing it for a project).  I'm going to close this for now.  If you're really interested in adding the functionality and can add in in a way that is optional and adds no additional overhead, I'm definitely up for the conversation!
